workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: halcyonazure/lsky-pro-docker
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    http: 8089
networkLimits:
  enabled: true
  egress: 2M
  ingress: 2M
resources:
  limits:
    cpu: 300m
    memory: 512Mi
    ephemeral-storage: 2Gi
  requests:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 1Gi
persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /var/www/html
env:
  env1:
    name: WEB_PORT
    value: '8089'
    description: 容器内Apache监听的端口
    title: Web端口
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/lsky-pro.png"
