apiVersion: v2
name: mblog
version: v1.0.0
appVersion: latest
description: 一个支持自部署的前后端分离的微博系统，可单用户或多用户使用
icon: https://images.budiuyun.net/i/2025/06/09/6846eaea44af8.png
maintainers:
  - name: niehaoran
    email: 179866495@qq.com
annotations:
  budiu/app-category-zh: 网站建设
