workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: easytier/easytier
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  ports:
    easytier: 11010
networkLimits:
  enabled: true
  egress: 10M
  ingress: 10M
resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 50m
    memory: 128Mi
    ephemeral-storage: 256Mi
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /etc/easytier
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器时区
    title: 时区
  env2:
    name: EASYTIER_NETWORK
    value: default-network
    description: EasyTier网络名称
    title: 网络名称
  env3:
    name: EASYTIER_SECRET
    value: your-secret-key
    description: EasyTier网络密钥
    title: 网络密钥
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/easytier.png" 