workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: itushan/mtab
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    http: 80
networkLimits:
  enabled: true
  egress: 2M
  ingress: 2M
resources:
  limits:
    cpu: 300m
    memory: 512Mi
    ephemeral-storage: 2Gi
  requests:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 1Gi
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /app
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/mtab.png"
