workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: halohub/halo
  tag: '2.21'
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: http
      port: 8090
      protocol: TCP
networkLimits:
  enabled: true
  egress: 10M
  ingress: 10M
resources:
  limits:
    cpu: 200m
    memory: 512Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /root/.halo2
env:
  env1:
    name: NGINX_MODE
    value: production
    description: Nginx运行模式
    title: 运行模式
  env2:
    name: NGINX_WORKER_PROCESSES
    value: auto
    description: Nginx工作进程数量
    title: 工作进程数
icon: https://images.budiuyun.net/i/2025/06/18/6852aabcdad48.png
