workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: yidadaa/chatgpt-next-web
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
networkLimits:
  enabled: true
  egress: 5M
  ingress: 5M
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
    ephemeral-storage: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 1Gi
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /app/data
env:
  env1:
    name: OPENAI_API_KEY
    value: ''
    description: OpenAI API密钥，用于访问ChatGPT API
    title: OpenAI API密钥
  env2:
    name: CODE
    value: ''
    description: 访问密码，用于保护您的应用
    title: 访问密码
  env3:
    name: BASE_URL
    value: https://api.openai.com
    description: API请求的基本URL
    title: API基本URL
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/chatgptnextweb.png"
