workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: jetbrains/qodana-js
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    http: 8080
networkLimits:
  enabled: true
  egress: 2M
  ingress: 2M
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
    ephemeral-storage: 10Gi
  requests:
    cpu: 1000m
    memory: 2Gi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /data
env:
  env1:
    name: QODANA_PROJECT_DIR
    value: /data/project
    description: 要分析的项目目录路径
    title: 项目目录
  env2:
    name: QODANA_REPORT_DIR
    value: /data/results
    description: 分析报告输出目录
    title: 报告目录
  env3:
    name: QODANA_SHOW_REPORT
    value: 'true'
    description: 是否在分析完成后显示报告
    title: 显示报告
  env4:
    name: QODANA_TOKEN
    value: ''
    description: Qodana Cloud令牌
    title: 令牌
icon: https://images.budiuyun.net/i/2025/06/09/6846ea7a9845d.png
