workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: linuxserver/rustdesk
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    http: 3000
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 300m
    memory: 384Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 150m
    memory: 128Mi
    ephemeral-storage: 256Mi
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /config
env:
  env1:
    name: PUID
    value: '1000'
    description: 容器内运行用户的UID
    title: 用户UID
  env2:
    name: PGID
    value: '1000'
    description: 容器内运行用户的GID
    title: 用户GID
  env3:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器时区
    title: 时区
  env4:
    name: CUSTOM_USER
    value: abc
    description: WEB界面HTTP Basic认证用户名，默认abc
    title: HTTP认证用户名
  env5:
    name: PASSWORD
    value: abc
    description: WEB界面HTTP Basic认证密码，默认abc
    title: HTTP认证密码
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/rustdesk.png"
