workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: wordpress
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    http: 80
networkLimits:
  enabled: true
  egress: 2M
  ingress: 2M
resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /var/www/html
icon: https://images.budiuyun.net/i/2025/06/09/6846911733f80.png
