workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: soulter/astrbot
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: http
      port: 6185
      protocol: TCP
networkLimits:
  enabled: true
  egress: 10M
  ingress: 10M
resources:
  limits:
    cpu: 400m
    memory: 1024Mi
    ephemeral-storage: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi
    ephemeral-storage: 512Mi
persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /app/data
env:
  env1:
    name: ADMIN_PASSWORD
    value: astrbot
    description: 管理员密码，请务必修改
    title: 管理员密码
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/astrbot.png"
