workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: calciumion/new-api
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /data
env:
  env2:
    name: TZ
    value: Asia/Shanghai
    description: 容器的时区设置
    title: 时区设置
icon: https://images.budiuyun.net/i/2025/07/03/6866219f5723d.png
