workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: homeassistant/home-assistant
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    web: 8123
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /config
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器时区
    title: 时区
icon: https://images.budiuyun.net/i/2025/06/14/684c4d6af303c.png
