workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: homeassistant/home-assistant
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    web: 8123
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
    ephemeral-storage: 3Gi
  requests:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 1Gi
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /config
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器时区
    title: 时区
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/home-assistant.png"
