apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nps.fullname" . }}
  labels:
    {{- include "nps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nps.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init-config
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "正在准备配置文件..."
              mkdir -p /config
              cp /configmap/* /config/
              echo "配置文件准备完成"
              ls -la /config
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: config
              mountPath: /configmap
            - name: nps-config
              mountPath: /config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              echo "Starting NPS with config path: /npsconf"
              /nps -conf=/npsconf
          {{- if .Values.service.ports }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          env:
            - name: CONF_PATH
              value: "/npsconf"
            {{- if .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $value.name }}
              value: {{ $value.value | quote }}
            {{- end }}
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "200m" }}
              memory: {{ .Values.resources.limits.memory | default "256Mi" }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.resources.requests.memory | default "128Mi" }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.path }}
            - name: nps-config
              mountPath: /npsconf
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "nps.fullname" . }}
        - name: config
          configMap:
            name: {{ include "nps.fullname" . }}-config
        - name: nps-config
          emptyDir: {}