apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nps.fullname" . }}
  labels:
    {{- include "nps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nps.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: config-init
          image: busybox
          command: ['sh', '-c', 'cp /config-readonly/* /config/ && chmod -R 755 /config/']
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: config-readonly
              mountPath: /config-readonly
            - name: config-writable
              mountPath: /config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.service.ports }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          env:
            - name: CONF_PATH
              value: "/conf"
            {{- if .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $value.name }}
              value: {{ $value.value | quote }}
            {{- end }}
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "200m" }}
              memory: {{ .Values.resources.limits.memory | default "256Mi" }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.resources.requests.memory | default "128Mi" }}
          volumeMounts:
          {{- range .Values.persistence.mounts }}
            - name: config-writable
              mountPath: {{ . }}
          {{- end }}
          stdin: true
          tty: true
      volumes:
        - name: config-readonly
          configMap:
            name: {{ include "nps.fullname" . }}-config
        - name: config-writable
          emptyDir: {}
      terminationGracePeriodSeconds: 30