workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: mcp/github-mcp-server
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    web: 8080
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: false
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /data
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器时区
    title: 时区
icon: https://images.budiuyun.net/i/2025/06/14/684c4eac00d3b.png
