apiVersion: v2
name: wireguard-easy
version: v1.0.0
appVersion: latest
description: 最简单的方式在任何Linux主机上安装和管理WireGuard
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/wireguard-easy.png"
maintainers:
  - name: 陈不丢
    email: 179866495@qq.com
sources:
  - https://github.com/wg-easy/wg-easy
annotations:
  budiu/app-category-zh: 网络工具
