workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: ghcr.nju.edu.cn
  repository: wg-easy/wg-easy
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: http
      port: 51821
      protocol: TCP
    - name: wireguard
      port: 51820
      protocol: UDP
networkLimits:
  enabled: true
  egress: 10M
  ingress: 10M
resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /etc/wireguard
securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - SYS_MODULE
  sysctls:
    - name: net.ipv4.conf.all.src_valid_mark
      value: "1"
    - name: net.ipv4.ip_forward
      value: "1"
env:
  env1:
    name: WG_HOST
    value: 'your-server-ip-or-domain'
    description: WireGuard服务器域名或IP地址(必填)
    title: WG_HOST
  env2:
    name: PASSWORD
    value: 'change-this-password'
    description: Web界面访问密码(必填)
    title: 密码
  env3:
    name: INSECURE
    value: 'false'
    description: 是否允许HTTP访问Web界面(不推荐)
    title: 不安全模式
icon: https://images.budiuyun.net/i/2025/06/15/684e6a8adcb5b.png
