apiVersion: v2
name: dashy
version: v1.0.0
appVersion: latest
description: Dashy是一个可自托管的个人仪表盘，包含状态检查、小部件、主题和图标包等功能
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/dashy.png"
maintainers:
  - name: 陈不丢
    email: 179866495@qq.com
annotations:
  budiu/app-category-zh: 运维监控
