workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: redis
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    redis: 6379
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /data
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器时区
    title: 时区
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/redis.png"
