workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: phpmyadmin
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    web: 80
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 1Gi
persistence:
  enabled: false
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts: []
env:
  env1:
    name: PMA_HOST
    value: db
    description: 要连接的MySQL服务器主机名
    title: MySQL主机
  env2:
    name: PMA_ARBITRARY
    value: '1'
    description: 允许在登录页自定义MySQL服务器地址
    title: 允许任意服务器
  env3:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器时区
    title: 时区
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/phpmyadmin.png"
