apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
  annotations:
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.mysql }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector: {{- include "mysql.selectorLabels" . | nindent 4 }} 