workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: yisier1/nps
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      protocol: TCP
    - name: web-udp
      port: 8080
      protocol: UDP
    - name: bridge
      port: 8024
      protocol: TCP
    - name: bridge-udp
      port: 8024
      protocol: UDP
    - name: bridge-tls
      port: 8025
      protocol: TCP
    - name: bridge-tls-udp
      port: 8025
      protocol: UDP
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local
  path: /conf/data
  mounts:
    - /conf
icon: https://images.budiuyun.net/i/2025/07/02/6864e19441383.jpg
