workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: eclipse-temurin
  tag: "22-jre"
  pullPolicy: IfNotPresent
command: ["java"]
# 可以通过覆盖javaOpts来自定义Java参数
javaOpts: "-Xms1g -Xmx4g"
args: ["-jar", "/app/read.jar"]
initContainer:
  enabled: true
  jarUrl: "https://github.com/autobcb/read/releases/download/v2.16.1/read.jar"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 1000m
    memory: 4Gi
    ephemeral-storage: 10Gi
  requests:
    cpu: 500m
    memory: 1Gi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /app
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器的时区
    title: 时区设置
  env2:
    name: JAVA_OPTS
    value: ''
    description: Java虚拟机参数（可选）
    title: Java参数
  env3:
    name: http_proxyHost
    value: ''
    description: HTTP代理服务器地址（可选）
    title: HTTP代理
  env4:
    name: http_proxyPort
    value: ''
    description: HTTP代理服务器端口（可选）
    title: HTTP代理端口
  env5:
    name: https_proxyHost
    value: ''
    description: HTTPS代理服务器地址（可选）
    title: HTTPS代理
  env6:
    name: https_proxyPort
    value: ''
    description: HTTPS代理服务器端口（可选）
    title: HTTPS代理端口
icon: https://images.budiuyun.net/i/2025/06/19/6854064e8b43a.png
