workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker-0.unsee.tech
  repository: bitnami/java
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 1000m
    memory: 2000Mi
    ephemeral-storage: 5Gi
  requests:
    cpu: 500m
    memory: 500Mi
    ephemeral-storage: 1Gi
persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /app
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 时区设置
    title: 时区
  env2:
    name: HTTP_PROXY
    value: ""
    description: HTTP代理设置(可选)
    title: HTTP代理
  env3:
    name: HTTPS_PROXY
    value: ""
    description: HTTPS代理设置(可选)
    title: HTTPS代理
command:
  enabled: true
  value: "java -jar /app/read.jar"
extraVolumeMounts:
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true
extraVolumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
icon: https://images.budiuyun.net/i/2025/07/03/6866263917409.png 