workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: read
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /app/storage
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器的时区
    title: 时区设置
  env2:
    name: http_proxyHost
    value: ''
    description: HTTP代理服务器地址（可选）
    title: HTTP代理
  env3:
    name: http_proxyPort
    value: ''
    description: HTTP代理服务器端口（可选）
    title: HTTP代理端口
  env4:
    name: https_proxyHost
    value: ''
    description: HTTPS代理服务器地址（可选）
    title: HTTPS代理
  env5:
    name: https_proxyPort
    value: ''
    description: HTTPS代理服务器端口（可选）
    title: HTTPS代理端口
icon: https://images.budiuyun.net/i/2025/06/19/6854064e8b43a.png
