workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker-0.unsee.tech
  repository: bitnami/java
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    http: 8080
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 1000m
    memory: 2000Mi
    ephemeral-storage: 5Gi
  requests:
    cpu: 500m
    memory: 500Mi
    ephemeral-storage: 1Gi
persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /app
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 时区设置
    title: 时区
command:
  enabled: true
  value: "java -jar /app/read.jar"
extraVolumeMounts:
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true
extraVolumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
icon: https://images.budiuyun.net/i/2025/06/19/6854064e8b43a.png 