apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kami-verify.fullname" . }}
  labels:
    {{- include "kami-verify.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kami-verify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kami-verify.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.service.ports }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $value.name }}
              value: {{ $value.value | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if and .Values.persistence.enabled .Values.persistence.mounts }}
          volumeMounts:
            {{- range $index, $path := .Values.persistence.mounts }}
            - name: data
              mountPath: {{ $path }}
            {{- end }}
            {{- if .Values.persistence.configFile.enabled }}
            - name: config-data
              mountPath: {{ .Values.persistence.configFile.mountPath }}
              subPath: {{ .Values.persistence.configFile.subPath }}
            {{- end }}
          {{- end }}
      {{- if and .Values.persistence.enabled .Values.persistence.mounts }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "kami-verify.fullname" . }}
        {{- if .Values.persistence.configFile.enabled }}
        - name: config-data
          persistentVolumeClaim:
            claimName: {{ include "kami-verify.fullname" . }}-config
        {{- end }}
      {{- end }}