{{- if .Values.persistence.configFile.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kami-verify.fullname" . }}-config
  labels:
    {{- include "kami-verify.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: 10Mi
{{- end }} 