workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: nextcloud
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    http: 80
networkLimits:
  enabled: true
  egress: 2M
  ingress: 2M
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
    ephemeral-storage: 3Gi
  requests:
    cpu: 200m
    memory: 512Mi
    ephemeral-storage: 1Gi
persistence:
  enabled: true
  size: 20Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /var/www/html
env:
  env1:
    name: MYSQL_DATABASE
    value: nextcloud
    description: MySQL/MariaDB数据库名
    title: 数据库名
  env2:
    name: MYSQL_USER
    value: nextcloud
    description: MySQL/MariaDB用户名
    title: 数据库用户名
  env3:
    name: MYSQL_PASSWORD
    value: ''
    description: MySQL/MariaDB用户密码
    title: 数据库密码
  env4:
    name: MYSQL_HOST
    value: ''
    description: MySQL/MariaDB主机地址
    title: 数据库主机
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/nextcloud.png"
