apiVersion: v2
name: cosyvoice
version: v1.0.0
appVersion: latest
description: 阿里开源 CosyVoice 语音合成/克隆，优化整合版
icon: https://images.budiuyun.net/i/2025/06/18/6852ae2d5286f.png
maintainers:
  - name: niehaoran
    email: 179866495@qq.com
sources:
  - https://github.com/harryliu888/cosyvoice
annotations:
  budiu/app-category-zh: 语音合成
