workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: harryliu888/cosyvoice
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: http
      port: 7860
      protocol: TCP
networkLimits:
  enabled: true
  egress: 5M
  ingress: 5M
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
    ephemeral-storage: 10Gi
  requests:
    cpu: 1000m
    memory: 2Gi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /app/data
env:
  env1:
    name: APP_MODE
    value: production
    description: 应用运行的模式
    title: 应用模式
icon: https://images.budiuyun.net/i/2025/06/18/6852ae2d5286f.png
