{{- if .Values.persistence.enabled }}
{{- range .Values.persistence.mounts }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" $ }}-{{ .name }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  accessModes:
    - {{ $.Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
{{- end }}
{{- end }} 