workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: niehaoran/personal-cloud-disk
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /var/www/html/uploads
icon: https://images.budiuyun.net/i/2025/06/19/6853e2a613712.png
