apiVersion: v2
name: uptime-kuma
version: v1.0.0
appVersion: 1.0.0
description: >-
  'Uptime Kuma 是一个开源、轻量的自托管监控工具，支持对网站、服务器和 API
  的正常运行时间进行实时监控，帮助用户快速了解服务的运行状况。它提供友好的用户界面、支持多种通知方式（如邮件、Telegram、Slack
    等）以及历史记录追踪功能。 '
icon: https://images.budiuyun.net/i/2025/05/13/6823632a4fc3c.png
maintainers:
  - name: niehaoran
    email: 179866495@qq.com
sources:
  - https://github.com/louislam/uptime-kuma
annotations:
  budiu/app-category-zh: 监控工具
