replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: louislam/uptime-kuma
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    port1: 3001
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 64m
    memory: 128Mi
persistence:
  enabled: true
  path: /app/data
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
env:
  env1:
    name: NODE_ENV
    value: production
    description: 应用运行的模式
    title: 应用模式
  env2:
    name: KUMA_DEBUG
    value: 'false'
    description: 是否开启调试模式
    title: 调试模式

icon: https://tuchuang.yunnaio.cn/i/2025/05/13/6823632a4fc3c.png