replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: louislam/uptime-kuma
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    port1: 3001
networkLimits:
  enabled: true
  egress: 2M
  ingress: 2M
resources:
  limits:
    cpu: 200m
    memory: 350Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 100m
    memory: 190Mi
    ephemeral-storage: 512Mi
persistence:
  enabled: true
  path: /app/data
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
env:
  env1:
    name: NODE_ENV
    value: production
    description: 应用运行的模式
    title: 应用模式
  env2:
    name: KUMA_DEBUG
    value: 'false'
    description: 是否开启调试模式
    title: 调试模式

icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/uptime-kuma.png"