apiVersion: v2
name: flarum
version: v1.0.0
appVersion: latest
description: Flarum是一个简约优雅的开源论坛软件
icon: https://images.budiuyun.net/i/2025/06/09/6846dedc7b5ec.png
maintainers:
  - name: niehaoran
    email: 179866495@qq.com
annotations:
  budiu/app-category-zh: 网站建设
