workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: cloudreve/cloudreve
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    http: 5212
networkLimits:
  enabled: true
  egress: 2M
  ingress: 2M
resources:
  limits:
    cpu: 500m
    memory: 1Gi
    ephemeral-storage: 10Gi
  requests:
    cpu: 200m
    memory: 512Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /cloudreve/uploads
    - /cloudreve/config
    - /cloudreve/db
env:
  env1:
    name: PUID
    value: '0'
    description: 容器内运行进程的用户UID
    title: 运行用户UID
  env2:
    name: PGID
    value: '0'
    description: 容器内运行进程的用户GID
    title: 运行用户GID
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/cloudreve.png"
