apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatgpt-next-web.fullname" . }}
  labels: {{- include "chatgpt-next-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector: {{- include "chatgpt-next-web.selectorLabels" . | nindent 4 }}