apiVersion: v2
name: minio
version: v1.0.0
appVersion: latest
description: MinIO 是一个高性能的多云对象存储服务，兼容 Amazon S3 API，适用于机器学习、分析和应用数据等多种场景。
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/minio.png"
sources:
  - https://github.com/minio/minio
  - https://hub.docker.com/r/minio/minio
maintainers:
  - name: 陈不丢
    email: 179866495@qq.com
annotations:
  budiu/app-category-zh: 内容管理
