workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: minio/minio
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    api: 9000
    console: 9001
networkLimits:
  enabled: true
  egress: 2M
  ingress: 2M
resources:
  limits:
    cpu: 500m
    memory: 1Gi
    ephemeral-storage: 10Gi
  requests:
    cpu: 200m
    memory: 512Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /data
env:
  env1:
    name: MINIO_ROOT_USER
    value: minioadmin
    description: MinIO 管理员用户名
    title: 管理员用户名
  env2:
    name: MINIO_ROOT_PASSWORD
    value: minioadmin
    description: MinIO 管理员密码
    title: 管理员密码
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/minio.png"
