apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easytier.fullname" . }}-config
  labels:
    {{- include "easytier.labels" . | nindent 4 }}
data:
  easytier.toml: |
    dhcp = true
    listeners = [
        "tcp://0.0.0.0:{{ .Values.easytier.ports.tcp }}",
        "udp://0.0.0.0:{{ .Values.easytier.ports.udp }}",
        "wg://0.0.0.0:{{ .Values.easytier.ports.wireguard }}",
        "ws://0.0.0.0:{{ .Values.easytier.ports.websocket }}/",
        "wss://0.0.0.0:{{ .Values.easytier.ports.wss }}/",
    ]
    rpc_portal = "0.0.0.0:0"
    tcp_whitelist = []
    udp_whitelist = []

    [network_identity]
    network_name = "{{ .Values.easytier.networkName }}"
    network_secret = "{{ .Values.easytier.networkSecret }}"

    [flags] 