workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.io
  repository: collabora/code
  tag: 24.04.10.2.1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    http: 9980
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 2000m
    memory: 2000Mi
    ephemeral-storage: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 1Gi
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /var/lib/coolwsd
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 时区设置
    title: 时区
  env2:
    name: extra_params
    value: "--o:ssl.enable=false"
    description: 额外参数
    title: 额外参数
  env3:
    name: aliasgroup1
    value: "https://.*:443"
    description: 域名别名组
    title: 域名别名组
command:
  enabled: true
  value: |
    /bin/bash
    -c
    /bin/su -s /bin/bash -c '/start-collabora-online.sh' cool
extraVolumeMounts:
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true
  - name: css-config
    mountPath: /usr/share/coolwsd/browser/dist/branding-desktop.css
    subPath: destop.css
    readOnly: true
extraVolumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
  - name: css-config
    configMap:
      name: filestash-wopi-css
      items:
        - key: destop.css
          path: destop.css
icon: https://images.budiuyun.net/i/2025/06/19/6854064e8b43a.png
