workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: niehaoran/ubuntu-ssh
  tag: '22.04'
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    ssh: 22
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 200m
    memory: 250Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 100m
    memory: 100Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /root
    - /home
    - /etc
    - /var/lib
    - /opt
    - /usr/local
    - /var/log
    - /tmp
env:
  env1:
    name: ROOT_PASSWORD
    value: budiu123
    description: SSH登录的root用户密码
    title: Root密码
  env2:
    name: TZ
    value: Asia/Shanghai
    description: 容器的时区设置
    title: 时区设置
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/ubuntu.png"
