workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: "budiu.yunnaio.cn"
  repository: niehaoran/python-vscode
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP

networkLimits:
  enabled: true
  egress: "5M"
  ingress: "5M"

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
    ephemeral-storage: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi
    ephemeral-storage: 512Mi

persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /home/coder/project
    - /home/coder/.config
    - /home/coder/.cache
    - /home/coder/.local

env:
  env1:
    name: CODE_SERVER_PASSWORD
    value: "python123"
    description: "code-server访问密码"
    title: "密码"
  env2:
    name: PYTHONUNBUFFERED
    value: "1"
    description: "Python输出无缓冲"
    title: "Python无缓冲输出"
  env3:
    name: PYTHONDONTWRITEBYTECODE
    value: "1"
    description: "禁止生成.pyc文件"
    title: "禁止字节码"
  env4:
    name: PIP_NO_CACHE_DIR
    value: "1"
    description: "禁用pip缓存"
    title: "禁用pip缓存"
  env5:
    name: PIP_DISABLE_PIP_VERSION_CHECK
    value: "1"
    description: "禁用pip版本检查"
    title: "禁用pip版本检查"
  env6:
    name: PYTHONPATH
    value: "/home/coder/project"
    description: "Python模块搜索路径"
    title: "Python路径"

icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/python-vscode.png" 