workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: aingdesk/aingdesk
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: http
      port: 7071
      protocol: TCP
networkLimits:
  enabled: true
  egress: 10M
  ingress: 10M
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
    ephemeral-storage: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 1Gi
persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /data
    - /uploads
    - /logs
    - /aingdesk/bin
    - /sys_data
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/aingdesk.png"
