apiVersion: v2
name: emlog
version: v1.0.0
appVersion: latest
description: emlog是一款基于PHP和MySQL的功能强大的博客及CMS建站系统
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/emlog.png"
maintainers:
  - name: 陈不丢
    email: 179866495@qq.com
sources:
  - https://github.com/emlog/emlog
annotations:
  budiu/app-category-zh: 网站建设
