workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: emlog/emlog
  tag: pro-latest-php7.4-apache
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    http: 80
networkLimits:
  enabled: true
  egress: 2M
  ingress: 2M
resources:
  limits:
    cpu: 400m
    memory: 512Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 3Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /var/www/html
env:
  env1:
    name: EMLOG_DOMAIN_NAME
    value: example.com
    description: emlog站点域名
    title: 域名
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/emlog.png"
