workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: rabbitmq
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    amqp: 5672
    management: 15672
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 512Mi
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /var/lib/rabbitmq
env:
  env1:
    name: RABBITMQ_DEFAULT_USER
    value: guest
    description: RabbitMQ 默认登录用户名
    title: 默认用户名
  env2:
    name: RABBITMQ_DEFAULT_PASS
    value: guest
    description: RabbitMQ 默认登录密码
    title: 默认密码
  env3:
    name: RABBITMQ_DEFAULT_VHOST
    value: /
    description: RabbitMQ 默认虚拟主机
    title: 默认虚拟主机
  env4:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器时区
    title: 时区
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/rabbitmq.png"
