apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autobcb-read.fullname" . }}
  labels:
    {{- include "autobcb-read.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "autobcb-read.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "autobcb-read.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init-volume
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          command:
            - /bin/bash
            - -c
            - |
              # 确保持久卷数据完整性
              {{- range $index, $path := .Values.persistence.mounts }}
              # 检查目录是否为空或不存在
              if [ ! -d "/data{{ $path }}" ] || [ -z "$(ls -A /data{{ $path }} 2>/dev/null)" ]; then
                echo "Initializing data for {{ $path }}"
                # 确保目标目录存在
                mkdir -p /data{{ $path }}
                # 使用cp保留所有属性和权限
                if [ -d "{{ $path }}" ]; then
                  # 复制所有文件并保留权限、所有权和链接
                  cp -rp {{ $path }}/* /data{{ $path }}/ 2>/dev/null || true
                  cp -rp {{ $path }}/.[^.]* /data{{ $path }}/ 2>/dev/null || true
                fi
                
                # 如果是/app目录，创建README文件而不是空的jar
                if [[ "{{ $path }}" == "/app" ]]; then
                  echo "Creating README file in /app directory"
                  cat > /data/app/README.txt << EOF
请上传read.jar文件到此目录。

您可以使用以下命令上传:
kubectl cp /path/to/your/read.jar POD_NAME:/app/read.jar -n NAMESPACE

上传完成后，重启Pod:
kubectl rollout restart deployment DEPLOYMENT_NAME -n NAMESPACE
EOF
                fi
              else
                echo "Directory /data{{ $path }} already initialized, skipping"
              fi
              {{- end }}
          {{- if and .Values.persistence.enabled .Values.persistence.mounts }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command.enabled }}
          command:
            - /bin/sh
            - -c
            - |
              if [ -f "/app/read.jar" ] && [ -s "/app/read.jar" ]; then
                echo "Starting application with read.jar"
                {{ .Values.command.value }}
              else
                echo "ERROR: read.jar not found or empty!"
                echo "Please upload read.jar file to the persistent volume."
                echo "See /app/README.txt for instructions."
                # 保持容器运行，不退出，这样用户可以连接到容器上传文件
                echo "Container will sleep for 1 hour before checking again..."
                sleep 3600
              fi
          {{- end }}
          {{- if .Values.service.ports }}
          ports:
            {{- range $name, $port := .Values.service.ports }}
            - name: {{ $name }}
              containerPort: {{ $port }}
              protocol: TCP
            {{- end }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $value.name }}
              value: {{ $value.value | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if and .Values.persistence.enabled .Values.persistence.mounts }}
          volumeMounts:
            {{- range $index, $path := .Values.persistence.mounts }}
            - name: data
              mountPath: {{ $path }}
              subPath: {{ $path | trimPrefix "/" }}
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or (and .Values.persistence.enabled .Values.persistence.mounts) .Values.extraVolumes }}
      volumes:
        {{- if and .Values.persistence.enabled .Values.persistence.mounts }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "autobcb-read.fullname" . }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      {{- end }} 