workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: budiu.yunnaio.cn
  repository: zoeyvid/npmplus
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    admin: 81
    http: 80
    goaccess: 91
networkLimits:
  enabled: true
  egress: 1M
  ingress: 1M
resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 10Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /data
    - /opt/npmplus
env:
  env1:
    name: TZ
    value: Asia/Shanghai
    description: 设置容器时区
    title: 时区
  env2:
    name: ACME_EMAIL
    value: admin@example.org
    description: Let's Encrypt 证书申请邮箱
    title: ACME 邮箱
  env3:
    name: CLEAN
    value: 'true'
    description: 自动清理无效 certbot 证书
    title: 清理无效证书
icon: "https://pub-cceec1ab61b144cbbf184f36d84774f7.r2.dev/npmplus.png"
