workloadType: Deployment
replicaCount: 1
image:
  imageRegistry: docker.1ms.run
  repository: vitess/lite
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  ports:
    - name: vtctld-web
      port: 15991
      protocol: TCP
    - name: vtctld-grpc
      port: 15999
      protocol: TCP
    - name: vtgate-mysql
      port: 15306
      protocol: TCP
    - name: vtgate-grpc
      port: 15001
      protocol: TCP
networkLimits:
  enabled: true
  egress: 5M
  ingress: 5M
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
    ephemeral-storage: 10Gi
  requests:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 5Gi
persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClass: local
  mounts:
    - /vt/vtdataroot
env:
  env1:
    name: TOPOLOGY_FLAGS
    value: '-topo_implementation etcd2 -topo_global_server_address localhost:2379'
    description: Vitess拓扑服务器地址
    title: 拓扑服务器
  env2:
    name: CELL
    value: zone1
    description: Vitess单元名称
    title: 单元名称
icon: https://images.budiuyun.net/i/2025/06/18/6852d449655ba.png
