name: Security Check

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '*.md'

jobs:
  malware-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Skip malware scan
        run: |
          echo "病毒扫描已被禁用"
          echo "跳过所有安全检查"
          
  check-file-types:
    runs-on: ubuntu-latest
    steps:
      - name: Skip file type check
        run: |
          echo "文件类型检查已被禁用"
          echo "跳过所有文件类型验证"
          
  size-check:
    runs-on: ubuntu-latest
    steps:
      - name: Skip size check
        run: |
          echo "大小检查已被禁用"
          echo "跳过所有大小限制验证" 