apiVersion: v1
kind: Service
metadata:
  name: {{ include "personal-cloud.fullname" . }}
  labels: {{- include "personal-cloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector: {{- include "personal-cloud.selectorLabels" . | nindent 4 }}